### ISSUE TITLE
Compilation errors on breaking API changes in the Model Server

### ISSUE THREAD

**Issue by cdamus** [eclipse-emfcloud/coffee-editor#324]
The Model Server APIs have some new breaking changes that the Coffee Editor needs to adapt to:

- the `ModelServerLauncher` constructor now requires a `ModelServerModule` for Guice injection configuration
- the `ModelServerClient::subscribe` method has removed the `String` parameter for resource format

**Comment by cdamus** [comment]
It looks like there may be more updates required than just these two API changes. With my attempt to use the new `DefaultModelServerModule` and adapt the client subscription, attempting to open the coffee diagram results in a blank editor and a bunch of errors on the console, including:

```
root ERROR Error: Message header must separate key and value using :
    at headers.forEach (/Users/damus/git/coffee-editor/web/node_modules/vscode-ws-jsonrpc/node_modules/vscode-jsonrpc/lib/messageReader.js:57:23)
    at Array.forEach (<anonymous>)
    at MessageBuffer.tryReadHeaders (/Users/damus/git/coffee-editor/web/node_modules/vscode-ws-jsonrpc/node_modules/vscode-jsonrpc/lib/messageReader.js:54:17)
    at SocketMessageReader.onData (/Users/damus/git/coffee-editor/web/node_modules/vscode-ws-jsonrpc/node_modules/vscode-jsonrpc/lib/messageReader.js:157:43)
    at Socket.readable.on (/Users/damus/git/coffee-editor/web/node_modules/vscode-ws-jsonrpc/node_modules/vscode-jsonrpc/lib/messageReader.js:148:18)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
```

and

```
root INFO ModelServerBackendContribution: 0 [qtp1923634801-27] ERROR ModelServerRouting  - Cannot subscribe to 'file:/Users/damus/git/coffee-editor/backend/examples/SuperBrewer3000/superbrewer3000.coffee': modeluri is not a valid model resource

root INFO ModelServerBackendContribution: 12 [qtp1923634801-27] ERROR ModelServerRouting  - Cannot unsubscribe: invalid session
```

and this that I don't understand because my system is currently configured to use AdoptOpenJDK 11.0.9.1 JRE by default::

```
root ERROR [hosted-plugin: 10163] Error on activation of java { message:
   'Java 8 or more recent is required to run. Please download and install a recent JDK',
  label: 'Get the Java Development Kit',
  command: 'vscode.open',
  commandParam:
   _URI {
     scheme: 'http',
     authority: 'www.oracle.com',
     path: '/technetwork/java/javase/downloads/index.html',
     query: '',
     fragment: '',
     _formatted: null,
     _fsPath: null } }
```

I am trying to run with `run.sh` on the latest of my branch [324-api-changes](/cdamus/coffee-editor/tree/324-api-changes): cdamus/coffee-editor@b1f48f8a19aec87f755fed1848474ff13a7b98ce.

**Comment by eneufeld** [comment]
@tortmayr can you help?

**Comment by tortmayr** [comment]
Unfortunately not. I'm not familiar with the recent modelserver changes. Maybe @martin-fleck-at or @ndoschek can help with this

**Comment by ndoschek** [comment]
We updated also the dependencies (e.g. to Eclipse 2020-09). I tested the newest modelserver version with `emfcloud/ecore-glsp` and updated the dependencies and did not get such errors. But I can have a look later this afternoon!
