### ISSUE TITLE
Multi client not working

### ISSUE THREAD

**Issue by aurelio-pennacchio** [eclipse-emfcloud/coffee-editor#413]
We are testing the multi-client feature of the GLSP's server. We found a problem. Step to reproduce the problem:

1. Clone and build the repository
2. Open the same coffee-editor (superbrewer3000.coffeenotation file) in two different browser's windows
3. Close superbrewer3000.coffeenotation file from one of the two tabs opened in your browser
4. Try to edit the model superbrewer3000.coffeenotation still opened 
5. You'll see the following exception as seen in the following screenshot

`
59606 [DefaultActionDispatcher 1] ERROR org.eclipse.glsp.server.jsonrpc.DefaultGLSPServer  - [ERROR] Could not process message:ActionMessage [action=deleteElement, clientId=workflow-diagram-notation:file:///homegit-projects/coffee-editor/backend/examples/SuperBrewer3000/superbrewer3000.coffeenotation]
org.eclipse.glsp.server.protocol.GLSPServerException: The session for client 'workflow-diagram-notation:file:///home/git-projects/coffee-editor/backend/examples/SuperBrewer3000/superbrewer3000.coffeenotation' has not been initialized yet. Could not process action: Operation [kind=deleteElement]
	at org.eclipse.glsp.server.internal.action.DefaultActionDispatcher.runAction(DefaultActionDispatcher.java:209)
	at org.eclipse.glsp.server.internal.action.DefaultActionDispatcher.handleMessage(DefaultActionDispatcher.java:181)
	at org.eclipse.glsp.server.internal.action.DefaultActionDispatcher.handleNextMessage(DefaultActionDispatcher.java:166)
	at org.eclipse.glsp.server.internal.action.DefaultActionDispatcher.runThread(DefaultActionDispatcher.java:153)
	at java.base/java.lang.Thread.run(Thread.java:829)
`

Is there any solution to this problem? Thank you for your support!

**Comment by eneufeld** [comment]
Hi @aurelio-pennacchio ,
did you use the master branch of the coffee editor?
