### ISSUE TITLE
Autocorrection is broken

### ISSUE THREAD

**Issue by felixalleweldt** [eclipse-emfcloud/coffee-editor#443]
When opening the superbrewer3000.wfconfig an error message pops up and the language server does not detect grammar errors.

**Occurs on:**

**Steps to reproduce**

- start the coffee-editor
- open _superbrewer3000.wfconfig_ 
    - The following error message appears: `Activating extension 'coffee-workflow-analyzer-editor' failed: Cannot find module '/tmp/vscode-unpacked/coffee-workflow-analyzer-editor-0.7.0.vsix/extension/out/extension.js' Require stack: - /coffee-editor/web/node_modules/@theia/core/lib/node/dynamic-require.js - /coffee-editor/web/node_modules/@theia/plugin-ext/lib/hosted/node/plugin-host-rpc.js - /coffee-editor/web/node_modules/@theia/plugin-ext/lib/hosted/node/plugin-host.js`
- add a second "medium" to line 8.
    - it is not detected as wrong grammar.

![medium](https://user-images.githubusercontent.com/65870537/167826548-681cd97e-ebce-4636-8880-21c4939d0dc9.png)

**Comment by eneufeld** [comment]
Thank you for the report, we will take a look

**Comment by eneufeld** [comment]
Hi @felixalleweldt,
I checked the current behavior. You are right it does not work on first start. It works if you reload the webpage. It seems there is a timing issue on connecting to the model server. We need to investigate. Thank you for pointing out the error.

**Comment by felixalleweldt** [comment]
Hello @eneufeld,

do you just press "reload" after the error message pops up? I did, but I did not get the syntax high lightening to show up. I tried it some times. Is there one more trick to get it to work?

Thanks
Felix

**Comment by eneufeld** [comment]
Hmm, 
I didn't get an error message. 
Are you on the current master?
Can you check that all build steps succeeded?
Which Java version are you using?

**Comment by felixalleweldt** [comment]
Hello,

I did a fresh checkout and built the docker file again.

My java version is
```

openjdk version "11.0.15" 2022-04-19
OpenJDK Runtime Environment (build 11.0.15+10-Ubuntu-0ubuntu0.22.04.1)
OpenJDK 64-Bit Server VM (build 11.0.15+10-Ubuntu-0ubuntu0.22.04.1, mixed mode, sharing)
```

I get this exception, see the attached logfile for the full built
[Log_19_05_2022.txt](https://github.com/eclipse-emfcloud/coffee-editor/files/8734272/Log_19_05_2022.txt)
.

```
root INFO [hosted-plugin: 589] PLUGIN_HOST(589): PluginManagerExtImpl/loadPlugin(/tmp/vscode-unpacked/coffee-workflow-analyzer-editor-0.7.0.vsix/extension/out/extension.js)
root ERROR [hosted-plugin: 589] Activating extension 'coffee-workflow-analyzer-editor' failed: Error: Cannot find module '/tmp/vscode-unpacked/coffee-workflow-analyzer-editor-0.7.0.vsix/extension/out/extension.js'
Require stack:
- /coffee-editor/web/node_modules/@theia/core/lib/node/dynamic-require.js
- /coffee-editor/web/node_modules/@theia/plugin-ext/lib/hosted/node/plugin-host-rpc.js
- /coffee-editor/web/node_modules/@theia/plugin-ext/lib/hosted/node/plugin-host.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Function.module._load (/coffee-editor/web/node_modules/@theia/plugin-ext-vscode/lib/node/plugin-vscode-init.js:68:33)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.dynamicRequire (/coffee-editor/web/node_modules/@theia/core/lib/node/dynamic-require.js:28:12)
    at Object.loadPlugin (/coffee-editor/web/node_modules/@theia/plugin-ext/lib/hosted/node/plugin-host-rpc.js:120:46)
    at /coffee-editor/web/node_modules/@theia/plugin-ext/lib/plugin/plugin-manager.js:212:48
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async PluginManagerExtImpl.$activatePlugin (/coffee-editor/web/node_modules/@theia/plugin-ext/lib/plugin/plugin-manager.js:271:13) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/coffee-editor/web/node_modules/@theia/core/lib/node/dynamic-require.js',
    '/coffee-editor/web/node_modules/@theia/plugin-ext/lib/hosted/node/plugin-host-rpc.js',
    '/coffee-editor/web/node_modules/@theia/plugin-ext/lib/hosted/node/plugin-host.js'
  ]
}
```

**Comment by eneufeld** [comment]
So you are running on Docker, don't know how that should influence this but we will check.

Can you check whether your `coffee-editor/web/browser-app/plugins` folder contains a `coffee-workflow-analyzer-editor-0.7.0.vsix`?

**Comment by felixalleweldt** [comment]
Yes, this file is there.

**Comment by eneufeld** [comment]
ok then the docker image is doing something weird, I double check, thank you

**Comment by neoq** [comment]
I reproduced @felixalleweldt's error with podman on d54d40125ca032e67b3e6ae1b3148effb634b85e .
I'm doing everything as root in the container.

I noticed that the "out" folder is missing from `/tmp/vscode-unpacked/coffee-workflow-analyzer-editor-0.7.0.vsix/extension`

The the log from ./run.sh -bcf and afterwards yarn start is attached.
[log.txt](https://github.com/eclipse-emfcloud/coffee-editor/files/8840725/log.txt)

**Comment by philip-iii** [comment]
As stupid as it sounds, simply copying the `lib` to `out` inside `/tmp/vscode-unpacked/coffee-workflow-analyzer-editor-0.7.0.vsix/extension` seems to fix the issue:

```
theia@deb8e2c945d7:/tmp/vscode-unpacked/coffee-workflow-analyzer-editor-0.7.0.vsix/extension$ cp -R lib out 
```
Somewhere in the build process or in the dependency specifications it seems that `lib` is used instead of `out` (or vice versa).

**Comment by philip-iii** [comment]
Could it be that:

https://github.com/eclipse-emfcloud/coffee-editor/blob/d54d40125ca032e67b3e6ae1b3148effb634b85e/web/coffee-workflow-analyzer-editor/package.json#L52

should instead be:
```
  "main": "lib/extension.js",
```

**Comment by tortmayr** [comment]
Actually vscode-extensions typically use `out` as output directory for the generated js files. 
So IMO we should instead adapt the tsconfig

https://github.com/eclipse-emfcloud/coffee-editor/blob/d54d40125ca032e67b3e6ae1b3148effb634b85e/web/coffee-workflow-analyzer-editor/tsconfig.json#L5

should be : 
```json
 "outdir": "out",
```

**Comment by philip-iii** [comment]
..or that.. Both were changed back and forth it seems, but the `tsconfig.json` was changed more recently indicating "Update to latest versions" so I assumed (naively) that was how it was "intended" to be, for one reason or another.. Either way, a fix would be appreciated!
